import { Schedule } from 'directed';
import type { World } from 'koota';
import { applyInput } from './apply-input';
import { cleanupSpatialHashMap } from './cleanup-spatial-hash-map';
import { dampPlayerMovement } from './damp-player-movement';
import { followPlayer } from './follow-player';
import { handleShooting } from './handle-shooting';
import { pollInput } from './poll-input';
import { pushEnemies } from './push-enemies';
import { spawnEnemies } from './spawn-enemies';
import { tickExplosion } from './tick-explosion';
import { tickShieldVisibility } from './tick-shield-visibility';
import { updateAutoRotate } from './update-auto-rotate';
import { updateAvoidance } from './update-avoidance';
import { updateBullets } from './update-bullet';
import { updateBulletCollisions } from './update-bullet-collisions';
import { updateMovement } from './update-movement';
import { updateSpatialHashing } from './update-spatial-hashing';
import { updateTime } from './update-time';

export const schedule = new Schedule<{ world: World }>();

schedule.add(updateTime);
schedule.add(pollInput);
schedule.add(spawnEnemies);
schedule.add(followPlayer);
schedule.add(updateAvoidance);
schedule.add(applyInput);
schedule.add(dampPlayerMovement);
schedule.add(pushEnemies);
schedule.add(handleShooting);
schedule.add(updateMovement);
schedule.add(updateBullets);
schedule.add(updateBulletCollisions);
schedule.add(updateAutoRotate);
schedule.add(updateSpatialHashing);
schedule.add(cleanupSpatialHashMap);
schedule.add(tickShieldVisibility);
schedule.add(tickExplosion);

schedule.build();
