packages:
    - packages/*
    - benches/*
    - .config/*

catalog:
    '@react-three/drei': ^10.6.1
    '@react-three/fiber': ^9.3.0
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6
    '@types/three': ^0.177.0
    esbuild-plugin-inline-functions: ^0.2.0
    react: ^19.1.1
    react-dom: ^19.1.1
    three: ^0.177.0
    directed: ^0.1.6
    vitest: ^3.2.4
    vite: ^6.3.5

manage-package-manager-versions: true

onlyBuiltDependencies:
    - esbuild
